version: "1"
services:
  frontend:
    image: engmarwen/samsar:frontend-1.2
    ports:
      - 5173:80
    environment:
      API_URL: "http://localhost:4000"
      FIREBASE_API_KEY: "AIzaSyDxxlLzE6XtYske4-XYMqFc68Rj_RxAMEE"
