name: CI/CD aiMicroservice

on:
  push:
    paths:
      - "aiMicroservice/**"
      - ".github/workflows/aimicroservice.yaml"
    branches: [main]
  pull_request:
    paths:
      - "aiMicroservice/**"
      - ".github/workflows/aimicroservice.yaml"
    branches: [main]

env:
  SERVICE_NAME: aiMicroservice
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/samsar
jobs:
